name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/**
      - develop
      - release

jobs:
  test:
    name: Test on JDK11
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Test with Gradle
        run: ./gradlew test